<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<title>${city.cityName}</title>-->
</head>
<body>
<h1>its working...</h1>
<!--<h3>Город - ${city.cityName}</h3>
<br>
<form method="post" action="/cities/${city.id}/update">
    <input name="cityName" value="${user.cityName}">
    <input type="submit" value="Сохранить")>
</form>-->
</body>
</html>